### ISSUE TITLE
Sostituzione lettere accentate

### ISSUE THREAD

**Issue by lucasaba** [genius-crm/Vtiger-6.X-lingua-ITA#10]
In alcuni file ci sono ancora i caratteri italiani accentati.
Sto provvedendo a sostituirli con i corrispettivi codici HTML.

I file che verranno modificati sono:
modules/Invoice.php
modules/MailManager.php
modules/Portal.php
modules/PurchaseOrder.php
modules/Quotes.php
modules/Reports.php
modules/SalesOrder.php
modules/Vtiger.php
modules/Settings/LayoutEditor.php
modules/Settings/MailConverter.php
modules/Settings/SharingAccess.php
modules/Settings/Vtiger.php
modules/Settings/Workflows.php
modules/Settings/ModuleManager.php
modules/Settings/CustomerPortal.php
modules/Settings/PickListDependency.php

**Comment by barra** [comment]
Luca, grazie per il prezioso contributo!
