### ISSUE TITLE
Tracking delle modifiche sul master di vtiger

### ISSUE THREAD

**Issue by lucasaba** [genius-crm/Vtiger-6.X-lingua-ITA#12]
Questa è più che altro una domanda: è possibile che su vtiger aggiornino i file delle lingue aggiungendo o togliendo testi ?
Perché nel caso potrei creare un automatismo per tracciare le eventuali modifiche.

**Comment by barra** [comment]
si, capita che aggiungano qualcosa, ma i cambiamenti nelle ultime 3 release sono stati così scarsi che abbiamo preferito monitorare manualmente i cambiamenti.

**Comment by lucasaba** [comment]
Allora, per ora, chiuderei
