### ISSUE TITLE
Modulo progetti

### ISSUE THREAD

**Issue by barra** [genius-crm/Vtiger-6.X-lingua-ITA#4]
i project task sono tradotti in alcuni casi come "compiti" in altri come "operazioni". 

Proporrei di uniformare. Operazioni non mi piace, compiti è ridondante con quelli presenti sul calendario. un "attività di progetto", abbreviato ad attività dove serve più corto?

**Comment by simonetravaglini** [comment]
io li chiamerei compiti di progetto, perchè è il nome giusto nel project management. E' un pò lungo e potrebbe portare a confusione, però mi sembra il più adeguato...

**Comment by barra** [comment]
Rinominato in compiti di progetto

https://github.com/genius-crm/Vtiger-6.X-lingua-ITA/commit/2edad1c4ff06dc1de11a8240e7c5e6dfd7ae0ee9
