### ISSUE TITLE
Follow-up

### ISSUE THREAD

**Issue by barra** [genius-crm/Vtiger-6.X-lingua-ITA#5]
C'è da correggere la traduzione.

Propongo di lasciarlo in inglese.

**Comment by simonetravaglini** [comment]
Si lasciamolo in inglese

**Comment by barra** [comment]
Fix: https://github.com/genius-crm/Vtiger-6.X-lingua-ITA/commit/ce1ef20cef5ee50b3295a4a27f714581ae16a702
